export const translations = {
    en: {
        title: "Bloodhound Forensics",
        live_filter_placeholder: "Live BPF Filter (e.g. tcp.port == 80)",
        disconnected: "Disconnected",
        live: "Live",
        pkts: "Pkts:",
        data_used: "Data:",
        visible_rows: "Visible:",
        reset_in: "Reset:",
        days: "d",
        hours: "h",
        mins: "m",
        secs: "s",
        legend_btn: "Legend",
        lang_btn: "ES", // Button shows the OTHER language to switch to
        factory_reset_btn: "FACTORY RESET",
        factory_reset_confirm: "ATTENTION! This will permanently delete ALL forensic database evidence (attacks, connections, and packets). Are you sure?",
        vuln_alerts: "Vulnerabilities / Alerts",
        reset_btn: "Reset",
        alert_type: "Alert Type / Context",
        occurrences: "Occurrences",
        recurring_conns: "Recurring Connections (IP:Port)",
        source_dest: "Source IP -> Dest IP : Port",
        packets_sent: "Packets Sent",
        realtime_filters: "Real-Time Context Filters",
        clear_filter: "Clear Filter",
        th_time: "Time",
        th_source: "Source",
        th_sport: "Sport",
        th_destination: "Destination",
        th_dport: "Dport",
        th_proto: "Proto",
        th_size: "Size",
        th_domain: "Domain",
        th_info: "Info / Alerts",
        legend_title: "Understanding Forensics Dashboard",
        legend_close: "Close",
        // Legend descriptions
        leg_red_title: "Red Rows (Critical Alerts)",
        leg_red_desc: "Packets flagged by the heuristic engine as critical threats (e.g., C2 Trojans, Botnets, Dark Web).",
        leg_filter_title: "Context Filters",
        leg_filter_desc: "Click on the top buttons (e.g., Botnet, Nmap) to instantly isolate traffic matching those threat signatures.",
        leg_bpf_title: "Live BPF Search",
        leg_bpf_desc: "Type free text (e.g., an IP, 'HTTP', '4444') to filter the visible packet history in real-time without losing data.",
        leg_stats_title: "Real-Time Statistics",
        leg_stats_desc: "The left panel aggregates the most frequent alerts and connections. Use the 'Reset' buttons to clear the SQLite history."
    },
    es: {
        title: "Bloodhound Forensics",
        live_filter_placeholder: "Filtro BPF en vivo (ej. tcp.port == 80)",
        disconnected: "Desconectado",
        live: "En vivo",
        pkts: "Pqts:",
        data_used: "Datos:",
        visible_rows: "Visibles:",
        reset_in: "Reset:",
        days: "días",
        hours: "hrs",
        mins: "min",
        secs: "seg",
        legend_btn: "Leyenda",
        lang_btn: "EN", // Button shows the OTHER language to switch to
        factory_reset_btn: "FACTORY RESET",
        factory_reset_confirm: "¡ATENCIÓN! Esto eliminará permanentemente TODA la evidencia forense de la base de datos (ataques, conexiones y paquetes). ¿Estás seguro?",
        vuln_alerts: "Vulnerabilidades / Alertas",
        reset_btn: "Limpiar",
        alert_type: "Tipo de Alerta / Contexto",
        occurrences: "Ocurrencias",
        recurring_conns: "Conexiones Recurrentes (IP:Puerto)",
        source_dest: "IP Origen -> IP Destino : Puerto",
        packets_sent: "Paquetes Enviados",
        realtime_filters: "Filtros de Contexto en Tiempo Real",
        clear_filter: "Quitar Filtro",
        th_time: "Tiempo",
        th_source: "Origen",
        th_sport: "P.Origen",
        th_destination: "Destino",
        th_dport: "P.Destino",
        th_proto: "Proto",
        th_size: "Tamaño",
        th_domain: "Dominio",
        th_info: "Info / Alertas",
        legend_title: "Entendiendo el Dashboard Forense",
        legend_close: "Cerrar",
        // Legend descriptions
        leg_red_title: "Filas Rojas (Alertas Críticas)",
        leg_red_desc: "Paquetes marcados por el motor heurístico como amenazas críticas (ej. Troyanos C2, Botnets, Dark Web).",
        leg_filter_title: "Filtros de Contexto",
        leg_filter_desc: "Haz clic en los botones superiores (ej. Botnet, Nmap) para aislar instantáneamente el tráfico que coincida con esas firmas.",
        leg_bpf_title: "Buscador BPF en Vivo",
        leg_bpf_desc: "Escribe texto libre (ej. una IP, 'HTTP', '4444') para filtrar el historial visible en tiempo real sin perder datos.",
        leg_stats_title: "Estadísticas en Tiempo Real",
        leg_stats_desc: "El panel izquierdo agrupa las alertas y conexiones más frecuentes. Usa 'Limpiar' para borrar el historial de SQLite."
    }
};
