export const translations = {
    en: {
        title: "Bloodhound Forensics",
        live_filter_placeholder: "Live BPF Filter (e.g. tcp.port == 80)",
        disconnected: "Disconnected",
        live: "Live",
        pkts: "Pkts:",
        data_used: "Data:",
        visible_rows: "Visible:",
        reset_in: "Reset:",
        days: "d",
        hours: "h",
        mins: "m",
        secs: "s",
        legend_btn: "Legend",
        lang_btn: "ES", // Button shows the OTHER language to switch to
        factory_reset_btn: "FACTORY RESET",
        factory_reset_confirm: "ATTENTION! This will permanently delete ALL forensic database evidence (attacks, connections, and packets). Are you sure?",
        vuln_alerts: "Vulnerabilities / Alerts",
        reset_btn: "Reset",
        alert_type: "Alert Type / Context",
        occurrences: "Occurrences",
        recurring_conns: "Recurring Connections (IP:Port)",
        source_dest: "Source IP -> Dest IP : Port",
        packets_sent: "Packets Sent",
        realtime_filters: "Real-Time Context Filters",
        clear_filter: "Clear Filter",
        th_time: "Time",
        th_source: "Source",
        th_sport: "Sport",
        th_destination: "Destination",
        th_dport: "Dport",
        th_proto: "Proto",
        th_size: "Size",
        th_domain: "Domain",
        th_info: "Info / Alerts",
        legend_title: "Understanding Forensics Dashboard",
        legend_close: "Close",
        // Legend descriptions
        leg_c2_title: "⚠️ TROJAN/C2",
        leg_c2_desc: "Someone on the network is running a remote access trojan or a backdoor. The device is calling command ports for Metasploit, Cobalt Strike, or similar (e.g. 4444, 4433, 1337).",
        leg_botnet_title: "🧟 IoT BOTNET",
        leg_botnet_desc: "A Camera, Smart TV, or Smart Bulb has been infected (e.g. Mirai Botnet) and is sending massive attacks to the internet using vulnerable ports (2323, 1900).",
        leg_crypto_title: "⛏️ CRYPTOMINER",
        leg_crypto_desc: "Hidden malware stealing power and CPU from a computer or phone to mine cryptocurrencies.",
        leg_dns_title: "⚠️ HIJACKED DNS",
        leg_dns_desc: "A device has a virus that changed its DNS settings. If the victim visits their bank, they will be silently redirected to a cloned page to steal their password.",
        leg_phishing_title: "🎣 PHISHING/DARKWEB",
        leg_phishing_desc: "A device attempted to resolve an .onion domain (Tor/DarkWeb) or a fake URL known for stealing credentials.",
        leg_nmap_title: "🕵️ NMAP SCAN",
        leg_nmap_desc: "A silent attacker is sending malformed packets (XMAS/NULL) to scan and discover which devices and ports are open on your network without being detected.",
        leg_plaintext_title: "🔓 PLAINTEXT",
        leg_plaintext_desc: "Someone is using unencrypted FTP, Telnet, or HTTP. Their passwords, emails, or sessions just traveled completely visible through the air.",
        leg_adware_title: "👁️ TRACKING/ADWARE",
        leg_adware_desc: "A TV or phone is sending abusive telemetry to advertising servers or silently tracking in the background.",
        leg_arp_title: "🔎 LOCAL SCAN (ARP)",
        leg_arp_desc: "An infected device on your home network is using ARP bursts to find other computers and phones to spread to.",
        leg_exfil_title: "📦 EXFILTRATION",
        leg_exfil_desc: "Suspiciously heavy traffic to the internet. Possible sign of massive databases being stolen to the cloud.",
        leg_syn_title: "SYN-SCAN",
        leg_syn_desc: "Noisy port scanning. A program is trying to connect to thousands of ports per second aggressively.",
        factory_reset_msg: "Are you sure you want to delete all historical logs and connections? This action is irreversible."
    },
    es: {
        title: "Bloodhound Forensics",
        live_filter_placeholder: "Filtro BPF en vivo (ej. tcp.port == 80)",
        disconnected: "Desconectado",
        live: "En vivo",
        pkts: "Pqts:",
        data_used: "Datos:",
        visible_rows: "Visibles:",
        reset_in: "Reset:",
        days: "días",
        hours: "hrs",
        mins: "min",
        secs: "seg",
        legend_btn: "Leyenda",
        lang_btn: "EN", // Button shows the OTHER language to switch to
        factory_reset_btn: "FACTORY RESET",
        factory_reset_confirm: "¡ATENCIÓN! Esto eliminará permanentemente TODA la evidencia forense de la base de datos (ataques, conexiones y paquetes). ¿Estás seguro?",
        vuln_alerts: "Vulnerabilidades / Alertas",
        reset_btn: "Limpiar",
        alert_type: "Tipo de Alerta / Contexto",
        occurrences: "Ocurrencias",
        recurring_conns: "Conexiones Recurrentes (IP:Puerto)",
        source_dest: "IP Origen -> IP Destino : Puerto",
        packets_sent: "Paquetes Enviados",
        realtime_filters: "Filtros de Contexto en Tiempo Real",
        clear_filter: "Quitar Filtro",
        th_time: "Tiempo",
        th_source: "Origen",
        th_sport: "P.Origen",
        th_destination: "Destino",
        th_dport: "P.Destino",
        th_proto: "Proto",
        th_size: "Tamaño",
        th_domain: "Dominio",
        th_info: "Info / Alertas",
        legend_title: "Entendiendo el Dashboard Forense",
        legend_close: "Cerrar",
        // Legend descriptions
        leg_c2_title: "⚠️ TROYANO/C2",
        leg_c2_desc: "Alguien en la red está ejecutando un troyano de acceso remoto o un backdoor. El dispositivo está llamando a puertos de comando de Metasploit, Cobalt Strike o similares (ej. 4444, 4433, 1337).",
        leg_botnet_title: "🧟 BOTNET IoT",
        leg_botnet_desc: "Una Cámara, Smart TV o Foco Inteligente de la casa ha sido infectado (Ej. Mirai Botnet) y está enviando ataques masivos hacia internet usando puertos vulnerables (2323, 1900).",
        leg_crypto_title: "⛏️ CRYPTOMINERO",
        leg_crypto_desc: "Malware oculto robando la energía y procesador de una computadora o celular para minar criptomonedas.",
        leg_dns_title: "⚠️ DNS SECUESTRADO",
        leg_dns_desc: "Un dispositivo tiene un virus que cambió sus configuraciones DNS. Si la víctima entra a la web de su banco, será redirigida silenciosamente a una página clonada falsa para robarle la contraseña.",
        leg_phishing_title: "🎣 PHISHING/DARKWEB",
        leg_phishing_desc: "Un dispositivo intentó resolver un dominio .onion (Tor/DarkWeb) o una URL falsa conocida por robar credenciales.",
        leg_nmap_title: "🕵️ ESCANEO NMAP",
        leg_nmap_desc: "Un atacante silencioso está enviando paquetes malformados (XMAS/NULL) para escanear y descubrir qué dispositivos y puertos están abiertos en tu red sin ser detectado.",
        leg_plaintext_title: "🔓 TEXTO PLANO",
        leg_plaintext_desc: "Alguien está usando FTP, Telnet o HTTP sin cifrar. Sus contraseñas, correos o sesiones acaban de viajar totalmente visibles por el aire.",
        leg_adware_title: "👁️ RASTREO/ADWARE",
        leg_adware_desc: "Un televisor o celular está enviando telemetría abusiva a servidores de publicidad o rastreo silencioso en segundo plano.",
        leg_arp_title: "🔎 ESCANEO LOCAL (ARP)",
        leg_arp_desc: "Un equipo infectado en tu red doméstica está usando ráfagas ARP para buscar a qué otras computadoras y celulares de tu casa puede propagarse.",
        leg_exfil_title: "📦 EXFILTRACIÓN",
        leg_exfil_desc: "Tráfico sospechosamente pesado hacia internet. Posible indicio de que se están robando bases de datos masivas hacia la nube.",
        leg_syn_title: "SYN-SCAN",
        leg_syn_desc: "Escaneo de puertos ruidoso. Un programa está intentando conectarse a miles de puertos por segundo de forma agresiva.",
        factory_reset_msg: "¿Estás seguro de que quieres eliminar todo el historial y las conexiones? Esta acción es irreversible."
    }
};
